// app/components/home/Brands.vue
<script setup lang="ts">
import { animate, stagger } from "motion-v";
import { useIntersectionObserver } from "@vueuse/core";
import { brands } from "~/utils/brands";

const invertedBrands = new Set([
  "Miche logo",
  "Speedsix logo",
  "Scicon logo",
  "Rocket logo",
]);

const sectionRef = ref<HTMLElement>();

function animateElements() {
  animate(
    "#brands > div.flex",
    { x: [-100, 0], opacity: [0, 1] },
    { duration: 1, delay: stagger(0.1) },
  );
}

useIntersectionObserver(
  sectionRef,
  ([entry]) => {
    if (entry?.isIntersecting) animateElements();
  },
  { threshold: 0.2 },
);
</script>

<template>
  <section
    id="brands"
    ref="sectionRef"
    data-color="dark"
    class="grid h-screen min-h-screen grid-cols-2 place-content-center place-items-center gap-[4.5rem] px-12 snap-start snap-always md:px-0 lg:w-1/3"
  >
    <div
      v-for="brand in brands"
      :key="brand.name"
      class="flex items-center justify-center"
    >
      <img
        :src="brand.image"
        :alt="brand.name"
        class="max-h-[2.6rem] md:max-h-[3.75rem]"
        :class="invertedBrands.has(brand.name) ? 'invert' : ''"
      />
    </div>
  </section>
</template>

// src/lib/components/home/Brands.svelte
<script lang="ts">
	import { animate, stagger } from 'motion';
	import inView from '$lib/actions/inView';
	import { elementColors } from '$lib/store';
	import { brands } from '$lib/brands';

	function animateElements() {
		$elementColors.logo = 'dark';
		$elementColors.burger = 'dark';
		$elementColors.copyright = 'dark';
		animate(
			'#brands > div.flex',
			{
				x: [-100, 0],
				opacity: [0, 1]
			},
			{ duration: 1, delay: stagger(0.1) }
		);
	}

	function handleExit() {
		$elementColors.logo = 'light';
		$elementColors.copyright = 'light';
	}
</script>

<section
	id="brands"
	class="min-h-screen h-screen grid grid-cols-2 gap-18 place-items-center place-content-center snap-start snap-always px-12 md:px-0 lg:w-1/3"
	use:inView={{ bottom: 100, top: 100 }}
	on:enter={animateElements}
	on:exit={handleExit}
>
	{#each brands as brand}
		<div class="flex items-center justify-center">
			{#if brand.name === 'Saffeti' || brand.name === 'SRM'}
				<img
					src={brand.image}
					alt={brand.name}
					class="max-h-[2.6rem] filter-invert-100 md:(max-h-15)"
				/>
			{:else}
				<img src={brand.image} alt={brand.name} class="max-h-[2.6rem] md:(max-h-15)" />
			{/if}
		</div>
	{/each}
</section>
