// src/lib/components/home/YoutubeFollow.svelte
<script lang="ts">
	import backgroundImage from '$lib/assets/main/avila-multisports-shared-bg.webp';

	function animateElements() {}
</script>

<section
	class="snap-start snap-always h-screen w-full relative overflow-hidden bg-cover z-1"
	style="background-image: url({backgroundImage});"
>
	<div
		class="relative w-full h-screen z-20 flex flex-col justify-center pl-6 pr-6 md:(pl-16 pr-10)"
	>
		<div>
			<div class="flex items-center">
				<div
					class="flex-shrink-0 w-20 h-20 bg-[#e3d268] rounded-full flex items-center justify-center z-1"
				>
					<div class="i-ph-youtube-logo-fill text-5xl text-[#003B49]" />
				</div>
				<div class="pl-8 pr-4 py-2 ml--4 bg-#003B49">
					<h2 class="text-white text-3xl md:text-4xl">Estamos en YouTube</h2>
				</div>
			</div>

			<p class="mt-6 text-white text-xl lg:text-3xl leading-relaxed py-6">
				Compartimos experiencias, entrenamientos y la filosofía que nos impulsa a vivir una vida
				activa y plena.
			</p>

			<a
				href="https://www.youtube.com/@Avilamultisport"
				target="_blank"
				rel="noopener noreferrer"
				class="inline-block mt-8 bg-[#003B49] text-white font-bold py-3 px-8 text-lg hover:bg-white transition-colors duration-300"
			>
				Visítanos
			</a>
		</div>
	</div>
</section>

// app/components/home/YoutubeFollow.vue
<script setup lang="ts">
import backgroundImage from "~/assets/main/avila-multisports-shared-bg.webp";
</script>

<template>
  <section
    id="youtube"
    data-color="light"
    class="relative z-[1] h-screen w-full snap-start snap-always overflow-hidden bg-cover"
    :style="{ backgroundImage: `url(${backgroundImage})` }"
  >
    <div
      class="relative z-20 flex h-screen w-full flex-col justify-center pr-6 pl-6 md:pr-10 md:pl-16"
    >
      <div>
        <div class="flex items-center">
          <div
            class="z-[1] flex h-20 w-20 flex-shrink-0 items-center justify-center rounded-full bg-[#e3d268]"
          >
            <Icon name="ph:youtube-logo-fill" class="text-5xl text-[#003B49]" />
          </div>
          <div class="-ml-4 bg-[#003B49] py-2 pr-4 pl-8">
            <h2 class="text-3xl text-white md:text-4xl">Estamos en YouTube</h2>
          </div>
        </div>

        <p class="mt-6 py-6 text-xl leading-relaxed text-white lg:text-3xl">
          Compartimos experiencias, entrenamientos y la filosofía que nos
          impulsa a vivir una vida activa y plena.
        </p>

        <a
          href="https://www.youtube.com/@Avilamultisport"
          target="_blank"
          rel="noopener noreferrer"
          class="mt-8 inline-block bg-[#003B49] px-8 py-3 text-lg font-bold text-white transition-colors duration-300 hover:bg-white"
        >
          Visítanos
        </a>
      </div>
    </div>
  </section>
</template>
