// src/lib/components/contact/ContactMap.svelte
<script lang="ts">
	import { elementColors, isDesktop } from '$lib/store';
	import { animate } from 'motion';
	import { onMount } from 'svelte';
	import { fade } from 'svelte/transition';

	let section: HTMLElement;

	onMount(() => {
		animate(
			[
				[
					'#map',
					{
						opacity: [0, 1],
						clipPath: [
							'polygon(0% 0%,100% 0%,100% 100%,0% 100%)',
							'polygon(0% 0%,100% 0%,100% 91%,0% 98.5%)'
						]
					},
					{ duration: 0.5, delay: 0.2 }
				],
				[
					'#map > img',
					{
						opacity: [0, 1],
						filter: ['blur(10px)', 'blur(0px)']
					},
					{ duration: 0.5, delay: 0.3 }
				],
				[
					'#mapFill',
					{
						opacity: [0, 1],
						clipPath: [
							'polygon(0% 0%,100% 0%,100% 100%,0% 100%)',
							$isDesktop
								? 'polygon(0% 0%, 100% 0%, 100% 88.75%, 0% 82.7%)'
								: 'polygon(0% 0%, 100% 0%, 100% 88.75%, 0% 83.06%)'
						]
					},
					{ duration: 0.5, delay: 0 }
				]
			],
			{
				duration: 2
			}
		);
		$elementColors.burger = 'dark';
	});
</script>

<section bind:this={section} class="w-full h-screen snap-start relative" transition:fade>
	<div id="map" class="bg-#003B49 h-84vh lg:h-81.4vh">
		<iframe
			class="w-full h-full"
			title="Mapa de ubicación de Avila Multisport"
			src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3921.429847040909!2d-66.87710482414072!3d10.510658764037924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c2a59116aaaaaab%3A0x75977b48cd36263e!2sCaracas%20MultiSport!5e0!3m2!1sen!2sve!4v1754673308965!5m2!1sen!2sve"
			style="border:0; z-index: 1;"
			allowfullscreen={false}
			loading="lazy"
			referrerpolicy="no-referrer-when-downgrade"
		></iframe>
	</div>
	<div
		id="mapFill"
		class="absolute top-0 right-0 bottom-0 [clip-path:polygon(0%_0%,_100%_0%,_100%_88.75%,_0%_83.06%)] bg-#ACC37E w-full -z-1 lg:h-97.2vh"
	/>
</section>

// app/components/contact/ContactMap.vue
<script setup lang="ts">
import { animate } from 'motion-v'

const { isDesktop } = useUiState()

onMounted(() => {
  animate(
    [
      [
        '#map',
        {
          opacity: [0, 1],
          clipPath: [
            'polygon(0% 0%,100% 0%,100% 100%,0% 100%)',
            'polygon(0% 0%,100% 0%,100% 91%,0% 98.5%)',
          ],
        },
        { duration: 0.5, delay: 0.2 },
      ],
      [
        '#map > img',
        { opacity: [0, 1], filter: ['blur(10px)', 'blur(0px)'] },
        { duration: 0.5, delay: 0.3 },
      ],
      [
        '#mapFill',
        {
          opacity: [0, 1],
          clipPath: [
            'polygon(0% 0%,100% 0%,100% 100%,0% 100%)',
            isDesktop.value
              ? 'polygon(0% 0%, 100% 0%, 100% 88.75%, 0% 82.7%)'
              : 'polygon(0% 0%, 100% 0%, 100% 88.75%, 0% 83.06%)',
          ],
        },
        { duration: 0.5, delay: 0 },
      ],
    ] as any,
    { duration: 2 },
  )
})
</script>

<template>
  <section
    id="contact-map"
    data-color="dark"
    class="relative h-screen w-full snap-start snap-always"
  >
    <div id="map" class="h-[84vh] bg-color-1 lg:h-[81.4vh]">
      <iframe
        class="h-full w-full"
        title="Mapa de ubicación de Avila Multisport"
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3921.429847040909!2d-66.87710482414072!3d10.510658764037924!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8c2a59116aaaaaab%3A0x75977b48cd36263e!2sCaracas%20MultiSport!5e0!3m2!1sen!2sve!4v1754673308965!5m2!1sen!2sve"
        style="border: 0; z-index: 1"
        :allowfullscreen="false"
        loading="lazy"
        referrerpolicy="no-referrer-when-downgrade"
      />
    </div>
    <div
      id="mapFill"
      class="absolute top-0 right-0 bottom-0 -z-[1] w-full bg-color-3 [clip-path:polygon(0%_0%,_100%_0%,_100%_88.75%,_0%_83.06%)] lg:h-[97.2vh]"
    />
  </section>
</template>
